### ISSUE TITLE
Passing nil arguments for get objection object

### ISSUE THREAD

**Issue by spbvasilenko** [atomicobject/objection#92]
Hey, I have a question

For example, in my class I have instancetype method for initial

- (instancetype)initWithName:(NSString *)name age:(NSInteger)age height:(NSInteger)height;

For get my class I'm use this code: 

Person *person = [[JSObjection defaultObjection] getObjectWithArgs: [Person class], name, age, height, nil];

For example, if parameter "age" will be nil, that I'm put to arguments for injection, after injection, "height" will be nil too :(

How resolve that bug?

**Comment by dewind** [comment]
Can you link to a project example of this happening?

**Comment by spbvasilenko** [comment]
https://github.com/spbvasilenko/ObjectionExample for example this project

**Comment by spbvasilenko** [comment]
I'm passing to Person class injector: List class, Age (that nil), Height (that 170)

But after injection "Height" is nil too, however I'm set 170 this parameter

**Comment by dewind** [comment]
Ah, thats because getObjectWithArgs is nil terminated. So if you pass a nil object it terminates the argument list. There isn't anyway around this unless you <code> getObject:argumentList:</code> and pass a NSNull object to it.

```objective-c
[[JSObjection defaultInjector] getObject: [Person class] argumentList: @[name, age, height]]
```

**Comment by spbvasilenko** [comment]
@dewind it's not worked, because I'm pass nil object to arguments array, and object not initialized. It's really critical problem of library.

**Comment by dewind** [comment]
Sigh, not really. You can’t pass nil objects to a nil terminated list. Which is why you have to use an NSArray instead if you want to pass nil objects via NSNull. Its a constraint of the language.


JUSTIN DEWIND

Project Consultant




Atomic Object

The right software can change everything.




o 616 776 6020

m 616 502 8383

**Comment by spbvasilenko** [comment]
Ok, thanks for your answers.
