### ISSUE TITLE
inScope:JSObjectionScopeSingleton doesn't work since Cocoapods version 1.6

### ISSUE THREAD

**Issue by pual** [atomicobject/objection#94]
I'm using the singleton registration (`[self bindClass:... inScope:JSObjectionScopeSingleton];`) in a `JSObjectionModule` in my app for quite a while.
After a pod update to version 1.6 the singleton scope is ignored and handled like `JSObjectionScopeNormal`.

**Comment by mpurland** [comment]
+1

**Comment by dewind** [comment]
Odd,

I'll look into it today.

**Comment by dewind** [comment]
I'm unable to reproduce the issue and I do have a test that exercises the "inScope" registration.

See https://github.com/atomicobject/objection/blob/develop/Specs/ModuleUsageSpecs.m#L172.

I'll need to have a code example to investigate further at this point. Also, its important that there aren't multiple revisions of Objection running within the project -- that can cause these kind of strange issues.

**Comment by zintus** [comment]
My quick investigation shown, that problem lies in absence of synthesize statement for lifeCycle property in JSObjectionProviderEntry.m file. This leads to usage of property getter defined in base class (JSObjectionEntry.m), always returning JSObjectionScopeNone.

**Comment by dewind** [comment]
Good catch. I'm disappointed that the tests are unable to reproduce it.

**Comment by zintus** [comment]
I'm happy to help!

**Comment by plu** [comment]
I'd help too, but I'm not sure what's the current state of the repo. If I try to run the test suites on Xcode 6.4, it doesn't even build. When I update `Quick` and `Nimble` submodules to latest master, it works. But then some tests are failing.

**Comment by dewind** [comment]
@plu Its running in travis and all tests are passing. I believe it is using the same version of XCode as well.

**Comment by plu** [comment]
@dewind I don't think so. It's using Xcode 6.1:

https://travis-ci.org/atomicobject/objection/builds/73209281

```
Xcode 6.1
Build version 6A1052c
```

You need to click on `announce` right next to `$ xcodebuild -version -sdk` to see the full output.

It's definitely broken on 6.4. What's your local setup? :)

**Comment by dewind** [comment]
@plu Similar to Travis CI. I'll need to get on a machine with 6.4 and address those issues ASAP. I'll open a new issue.

**Comment by plu** [comment]
Cool thanks! I can have a look at them too right now.

**Comment by plu** [comment]
What about cutting a new release 1.7? :)

**Comment by scottkilker** [comment]
Any updates on this issue?

**Comment by zintus** [comment]
Up

**Comment by dewind** [comment]
Sorry guys,

I'll review the issue this week.

**Comment by zintus** [comment]
@dewind gentle bump :)

**Comment by CapnSpellcheck** [comment]
This made it into 1.6.1 did it not? https://github.com/atomicobject/objection/releases/tag/1.6.1

**Comment by zintus** [comment]
Oh, I'm sorry 😬

Let's close issue then?

**Comment by pual** [comment]
Yes, it works now, thanks!
