### ISSUE TITLE
Getting a reference to the JSObjectionInjector which created an object?

### ISSUE THREAD

**Issue by mflint** [atomicobject/objection#97]
Hello team,

I sometimes need to get the `JSObjectionInjector` which was used to create an object, after the call to `-awakeFromObjection` has been performed, and would like to contribute a pull request to make this possible.

I can see two options:

1. add support for a `-awakeFromObjection:(JSObjectionInjector *)injector` function, so the injector can pass itself to the created object
2. add support for injecting the active `JSObjectionInjector` to a property, using Objection itself.

Would the maintainers have any preference? (Or a third, better way?)

Thanks for any advice you may have!

  Matthew

### Option 1
```
@property (nonatomic) JSObjectionInjector *injector;

-(void)awakeFromObjection:(JSObjectionInjector *)injector {
  self.injector = injector;
  ...
}
```

### Option 2
```
@property (nonatomic) JSObjectionInjector *injector;

objection_requires(@"injector")
```

**Comment by dewind** [comment]
The JSObjectFactory can be used inlieu of the JSObjectionFactory. It is a proxy to the JSObjectionInjector that you can use to build objects from the injector context.

**Comment by mflint** [comment]
Awesome, thank-you @dewind. That could be the magic I was searching for!
